### ISSUE TITLE
Selecting Daily tab and radio button behave weirdly

### ISSUE THREAD

**Issue by Sebashish** [sojinantony01/react-cron-generator#17] opened 2020-07-09 09:42 UTC
- babelify js is not behaving properly (dist).
- I tried installing package and use inside my react app.
- Could be because of the depicated life cycles and index as a key.

**How to produce**
- Click on Month tab
- Then try clicking on Daily tab. It will take you to Hour tab
- Second one is click on Daily tab and then switch between radion button.
- Selecting first radio button will again redirect you to Hour tab

React version:  "react": "^16.13.1"
package version: "react-cron-generator": "^1.2.5"

**Comment by WilliamPriorielloGarda** [comment] 2020-07-09 20:24
I have also noticed this, I think it is a regression for recent changes.

**Comment by SojinAntony** [comment] 2020-07-10 04:07
@Sebashish Thank you for reporting the issue, 
the issue was occurred due to some recent updates.
 Fixed in the latest version 1.2.6, Please update to the latest cron generator version
Thank you @WilliamPriorielloGarda

**Closed** 2020-07-13 15:22 UTC
Labels: Fixed, bug
